<script setup lang="ts">
import type { HeroSection } from '@/types/websitePlan'

const props = defineProps<{
  modelValue: HeroSection
}>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: HeroSection): void
  (e: 'regenerate', section: HeroSection): void
}>()

const updateField = (key: keyof HeroSection, value: any) => {
  emit('update:modelValue', { ...props.modelValue, [key]: value })
}

const handleRegenerate = () => {
  emit('regenerate', props.modelValue)
}
</script>

<template>
  <div class="border rounded-lg p-3 bg-slate-50/60">
    <header class="flex justify-between items-center mb-2">
      <span class="text-xs font-semibold uppercase tracking-wide text-slate-500">
        Hero section
      </span>
      <span class="text-[10px] text-slate-400">Draft generated by AI. You can edit.</span>
    </header>

    <div class="space-y-2 text-xs">
      <label class="block">
        Title
        <input
          class="mt-1 w-full border rounded px-2 py-1"
          :value="modelValue.title"
          @input="updateField('title', ($event.target as HTMLInputElement).value)"
        />
      </label>

      <label class="block">
        Body
        <textarea
          class="mt-1 w-full border rounded px-2 py-1"
          rows="3"
          :value="modelValue.body"
          @input="updateField('body', ($event.target as HTMLTextAreaElement).value)"
        />
      </label>

      <div class="grid gap-2 md:grid-cols-[1.3fr,1fr]">
        <label class="block">
          Primary CTA label
          <input
            class="mt-1 w-full border rounded px-2 py-1"
            :value="modelValue.primaryCtaLabel"
            @input="updateField('primaryCtaLabel', ($event.target as HTMLInputElement).value)"
          />
        </label>

        <label class="block">
          CTA target (optional)
          <input
            class="mt-1 w-full border rounded px-2 py-1"
            :value="modelValue.primaryCtaTarget || ''"
            @input="updateField('primaryCtaTarget', ($event.target as HTMLInputElement).value)"
          />
        </label>
      </div>
    </div>

    <div class="flex justify-end mt-3">
      <button
        type="button"
        class="px-3 py-1.5 text-xs rounded border border-blue-600 text-blue-700"
        @click="handleRegenerate"
      >
        Regenerate with AI
      </button>
    </div>
  </div>
</template>
